/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentalMobil;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dickypmngkss
 */
public class Mobil extends javax.swing.JFrame {

    /**
     * Creates new form Mobil
     */
    public Mobil() {
        initComponents();
        table();
        del();
    }
    
    public void table(){
        DefaultTableModel tb1 = new DefaultTableModel();
        tb1.addColumn("Kode");
        tb1.addColumn("Nama Mobil");
        tb1.addColumn("Merek");
        tb1.addColumn("Warna");
        tb1.addColumn("No Polisi");
        tb1.addColumn("No BPKB");
        tb1.addColumn("Harga");
        
        try {
            String host = "jdbc:mysql://localhost:3306/rental_mobil",
            user = "root",
            pass = "";
            Connection con = (Connection) DriverManager.getConnection(host, user, pass);
            Statement st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM mobil");
            
            while(rs.next()){
                tb1.addRow(new Object[] {
                    rs.getString("kode"),
                    rs.getString("nama_mobil"),
                    rs.getString("merek"),
                    rs.getString("warna"),
                    rs.getString("no_polisi"),
                    rs.getString("no_bpkb"),
                    rs.getString("harga"),
                });
            }
            tabelMobil.setModel(tb1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + e.getMessage());
        }
    }
    
    void del(){
        Kode.setText("");
        NMobil.setText("");
        Merek.setText("");
        Warna.setText("");
        NPolisi.setText("");
        NBpkb.setText("");
        Price.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Mobil_Label6 = new javax.swing.JLabel();
        Mobil_Kode = new javax.swing.JLabel();
        Mobil_NMobil = new javax.swing.JLabel();
        Mobil_MMobil = new javax.swing.JLabel();
        Mobil_WMobil = new javax.swing.JLabel();
        Mobil_NoMobil = new javax.swing.JLabel();
        Mobil_NoBPKB = new javax.swing.JLabel();
        Mobil_Price = new javax.swing.JLabel();
        Kode = new javax.swing.JTextField();
        NMobil = new javax.swing.JTextField();
        Merek = new javax.swing.JTextField();
        Warna = new javax.swing.JTextField();
        NPolisi = new javax.swing.JTextField();
        NBpkb = new javax.swing.JTextField();
        Mobil_SimpanData = new javax.swing.JButton();
        Price = new javax.swing.JTextField();
        Mobil_Kembali = new javax.swing.JButton();
        Mobil_HapusData = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelMobil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));

        jLabel2.setBackground(new java.awt.Color(176, 58, 48));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(176, 58, 48));
        jLabel2.setText("RENTAL CAR MANEGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(176, 58, 48));

        Mobil_Label6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Mobil_Label6.setForeground(new java.awt.Color(217, 217, 217));
        Mobil_Label6.setText("DATA MOBIL RENTAL");

        Mobil_Kode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_Kode.setForeground(new java.awt.Color(217, 217, 217));
        Mobil_Kode.setText("Kode");

        Mobil_NMobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_NMobil.setForeground(new java.awt.Color(217, 217, 217));
        Mobil_NMobil.setText("Nama Mobil");

        Mobil_MMobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_MMobil.setForeground(new java.awt.Color(217, 217, 217));
        Mobil_MMobil.setText("Merek");

        Mobil_WMobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_WMobil.setForeground(new java.awt.Color(217, 217, 217));
        Mobil_WMobil.setText("Warna");

        Mobil_NoMobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_NoMobil.setForeground(new java.awt.Color(217, 217, 217));
        Mobil_NoMobil.setText("No. Polisi");

        Mobil_NoBPKB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_NoBPKB.setForeground(new java.awt.Color(217, 217, 217));
        Mobil_NoBPKB.setText("No. BPKB");

        Mobil_Price.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_Price.setForeground(new java.awt.Color(217, 217, 217));
        Mobil_Price.setText("Harga");

        Kode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        NMobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Merek.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Warna.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        NPolisi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        NBpkb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NBpkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NBpkbActionPerformed(evt);
            }
        });

        Mobil_SimpanData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_SimpanData.setForeground(new java.awt.Color(176, 58, 48));
        Mobil_SimpanData.setText("SIMPAN");
        Mobil_SimpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mobil_SimpanDataActionPerformed(evt);
            }
        });

        Price.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Mobil_Kembali.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_Kembali.setForeground(new java.awt.Color(176, 58, 48));
        Mobil_Kembali.setText("KEMBALI");
        Mobil_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mobil_KembaliActionPerformed(evt);
            }
        });

        Mobil_HapusData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mobil_HapusData.setForeground(new java.awt.Color(176, 58, 48));
        Mobil_HapusData.setText("HAPUS ");
        Mobil_HapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mobil_HapusDataActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(176, 58, 48));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(217, 217, 217));
        jLabel1.setText("LIST MOBIL RENTAL");

        tabelMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMobil.setSelectionBackground(new java.awt.Color(176, 58, 48));
        tabelMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMobilMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelMobil);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Mobil_NoMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Mobil_Kode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(139, 139, 139))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(Kode)
                                            .addGap(39, 39, 39)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Mobil_NMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Mobil_NoBPKB, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Merek, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Mobil_MMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Mobil_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(Mobil_Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGap(39, 39, 39)
                                    .addComponent(NBpkb, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(43, 43, 43)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mobil_WMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Warna, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mobil_SimpanData, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Mobil_HapusData, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(937, 937, 937)
                            .addComponent(Mobil_Kembali))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Mobil_Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mobil_Kode)
                    .addComponent(Mobil_NMobil)
                    .addComponent(Mobil_MMobil)
                    .addComponent(Mobil_WMobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Merek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Warna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mobil_NoMobil)
                            .addComponent(Mobil_NoBPKB)
                            .addComponent(Mobil_Price))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NBpkb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Mobil_SimpanData, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mobil_HapusData))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Mobil_Kembali)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mobil_SimpanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mobil_SimpanDataActionPerformed
        // TODO add your handling code here:
        try {
        String host = "jdbc:mysql://localhost:3306/rental_mobil",
        user = "root",
        pass = "";
        Connection con = (Connection) DriverManager.getConnection(host, user, pass);
        
        String kode = Kode.getText();
        String nama_mobil = NMobil.getText();
        String merek = Merek.getText();
        String warna = Warna.getText();
        String no_polisi = NPolisi.getText();
        String no_bpkb = NBpkb.getText();
        String harga = Price.getText();
        
        Statement st = (Statement) con.createStatement();
        st.executeUpdate("INSERT INTO mobil ( kode, nama_mobil, merek, warna, no_polisi, no_bpkb, harga) VALUES ('"+kode+"', '"+nama_mobil+"', '"+merek+"', '"+warna+"', '"+no_polisi+"', '"+no_bpkb+"', '"+harga+"')");
        
        }catch(SQLException err) {
        JOptionPane.showMessageDialog(null, err.getMessage()); }
        
        table();
        del();
        
    }//GEN-LAST:event_Mobil_SimpanDataActionPerformed

    private void Mobil_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mobil_KembaliActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_Mobil_KembaliActionPerformed

    private void Mobil_HapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mobil_HapusDataActionPerformed
        // TODO add your handling code here:
        try {
            String host = "jdbc:mysql://localhost:3306/rental_mobil",
            user = "root",
            pass = "";
            Connection con = (Connection) DriverManager.getConnection(host, user, pass);

            String kode = Kode.getText();

            Statement st = (Statement) con.createStatement();
            st.executeUpdate("DELETE FROM mobil WHERE (kode) = '"+kode+"'");
        }catch(SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage()); 
        }
        
        table();
        del();
    }//GEN-LAST:event_Mobil_HapusDataActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            String host = "jdbc:mysql://localhost:3306/rental_mobil",
            user = "root",
            pass = "";
            Connection con = (Connection) DriverManager.getConnection(host, user, pass);

            String kode = Kode.getText();
            String nama_mobil = NMobil.getText();
            String merek = Merek.getText();
            String warna = Warna.getText();
            String no_polisi = NPolisi.getText();
            String no_bpkb = NBpkb.getText();
            String harga = Price.getText();

            Statement st = (Statement) con.createStatement();
            st.executeUpdate("UPDATE mobil SET nama_mobil='"+nama_mobil+"', merek='"+merek+"', warna='"+warna+"', no_polisi='"+no_polisi+"', no_bpkb='"+no_bpkb+"', harga='"+harga+"' WHERE kode='"+kode+"'");
        }catch(SQLException err) {
        JOptionPane.showMessageDialog(null, err.getMessage()); 
        }
    
        table();
        del();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabelMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMobilMouseClicked
        // TODO add your handling code here:
        int row = tabelMobil.rowAtPoint(evt.getPoint());
        String kode = tabelMobil.getValueAt(row, 0).toString();
        Kode.setText(kode);
        String mobil = tabelMobil.getValueAt(row, 1).toString();
        NMobil.setText(mobil);
        String merek = tabelMobil.getValueAt(row, 2).toString();
        Merek.setText(merek);
        String warna = tabelMobil.getValueAt(row, 3).toString();
        Warna.setText(warna);
        String polisi = tabelMobil.getValueAt(row, 4).toString();
        NPolisi.setText(polisi);
        String bpkb = tabelMobil.getValueAt(row, 5).toString();
        NBpkb.setText(bpkb);
        String price = tabelMobil.getValueAt(row, 6).toString();
        Price.setText(price);
    }//GEN-LAST:event_tabelMobilMouseClicked

    private void NBpkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NBpkbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NBpkbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Kode;
    private javax.swing.JTextField Merek;
    private javax.swing.JButton Mobil_HapusData;
    private javax.swing.JButton Mobil_Kembali;
    private javax.swing.JLabel Mobil_Kode;
    private javax.swing.JLabel Mobil_Label6;
    private javax.swing.JLabel Mobil_MMobil;
    private javax.swing.JLabel Mobil_NMobil;
    private javax.swing.JLabel Mobil_NoBPKB;
    private javax.swing.JLabel Mobil_NoMobil;
    private javax.swing.JLabel Mobil_Price;
    private javax.swing.JButton Mobil_SimpanData;
    private javax.swing.JLabel Mobil_WMobil;
    private javax.swing.JTextField NBpkb;
    private javax.swing.JTextField NMobil;
    private javax.swing.JTextField NPolisi;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Warna;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelMobil;
    // End of variables declaration//GEN-END:variables
}
