/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentalMobil;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dickypmngkss
 */
public class Penyewa extends javax.swing.JFrame {

    /**
     * Creates new form Penyewa
     */
    public Penyewa() {
        initComponents();
        table();
        del();
        LoadKodeMobil();
    }
    
    public void table(){
        DefaultTableModel tb1 = new DefaultTableModel();
        tb1.addColumn("No");
        tb1.addColumn("Nama Pelanggan");
        tb1.addColumn("NIK");
        tb1.addColumn("Mobil");
        tb1.addColumn("No Polisi");
        tb1.addColumn("Tgl Peminjaman");
        tb1.addColumn("Harga");
        
        try {
            String host = "jdbc:mysql://localhost:3306/rental_mobil",
            user = "root",
            pass = "";
            Connection con = (Connection) DriverManager.getConnection(host, user, pass);
            Statement st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM penyewa");
            
            while(rs.next()){
                tb1.addRow(new Object[] {
                    rs.getString("No"),
                    rs.getString("Nama"),
                    rs.getString("Nik"),
                    rs.getString("namaMobil"),
                    rs.getString("noPolisi"),
                    rs.getString("tglPinjam"),
                    rs.getString("Harga")
                });
            }
            tabelPenyewa.setModel(tb1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + e.getMessage());
        }
    }
    
    void del(){
        no.setText("");
        nama.setText("");
        nik.setText("");
        mobil.setText("");
        noPolisi.setText("");
        tglPinjam.setText("");
        harga.setText("");
    }
    
    public void LoadKodeMobil(){
        try {
            String host = "jdbc:mysql://localhost:3306/rental_mobil",
            user = "root",
            pass = "";
            
            Connection con = (Connection) DriverManager.getConnection(host, user, pass);
            PreparedStatement pst = con.prepareStatement("SELECT kode FROM mobil");
            ResultSet rs = pst.executeQuery();
            
            cmbKodeMobil.removeAllItems();
            
            while(rs.next()){
                cmbKodeMobil.addItem(rs.getString(1));
            }
            
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Biodata_Penyewa = new javax.swing.JLabel();
        Penyewa_Aplikasi = new javax.swing.JLabel();
        Penyewa_No = new javax.swing.JLabel();
        Penyewa_Nama = new javax.swing.JLabel();
        Penyewa_Mobil = new javax.swing.JLabel();
        Penyewa_NIK = new javax.swing.JLabel();
        Penyewa_plat = new javax.swing.JLabel();
        Penyewa_kodeMobil = new javax.swing.JLabel();
        Penyewa_TglPinjam = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        mobil = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        noPolisi = new javax.swing.JTextField();
        tglPinjam = new javax.swing.JTextField();
        Simpan_Data = new javax.swing.JButton();
        Lanjutkan = new javax.swing.JButton();
        Hapus_Data = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmbKodeMobil = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();
        Penyewa_harga = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPenyewa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(176, 58, 48));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));

        jLabel1.setBackground(new java.awt.Color(176, 58, 48));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(176, 58, 48));
        jLabel1.setText("RENTAL CAR MANEGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        jPanel2.setBackground(new java.awt.Color(176, 58, 48));

        Biodata_Penyewa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Biodata_Penyewa.setForeground(new java.awt.Color(217, 217, 217));
        Biodata_Penyewa.setText("PEMINJAMAN MOBIL");

        Penyewa_Aplikasi.setBackground(new java.awt.Color(217, 217, 217));
        Penyewa_Aplikasi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Penyewa_Aplikasi.setForeground(new java.awt.Color(217, 217, 217));
        Penyewa_Aplikasi.setText("LIST PEMINJAMAN MOBIL");

        Penyewa_No.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penyewa_No.setForeground(new java.awt.Color(217, 217, 217));
        Penyewa_No.setText("No");

        Penyewa_Nama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penyewa_Nama.setForeground(new java.awt.Color(217, 217, 217));
        Penyewa_Nama.setText("Nama ");

        Penyewa_Mobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penyewa_Mobil.setForeground(new java.awt.Color(217, 217, 217));
        Penyewa_Mobil.setText("Mobil");

        Penyewa_NIK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penyewa_NIK.setForeground(new java.awt.Color(217, 217, 217));
        Penyewa_NIK.setText("NIK");

        Penyewa_plat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penyewa_plat.setForeground(new java.awt.Color(217, 217, 217));
        Penyewa_plat.setText("Nomor Polisi");

        Penyewa_kodeMobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penyewa_kodeMobil.setForeground(new java.awt.Color(217, 217, 217));
        Penyewa_kodeMobil.setText("Kode Mobil");

        Penyewa_TglPinjam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penyewa_TglPinjam.setForeground(new java.awt.Color(217, 217, 217));
        Penyewa_TglPinjam.setText("Tanggal Peminjaman");

        no.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        nama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mobil.setEditable(false);
        mobil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        nik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        noPolisi.setEditable(false);
        noPolisi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tglPinjam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tglPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglPinjamActionPerformed(evt);
            }
        });

        Simpan_Data.setBackground(new java.awt.Color(217, 217, 217));
        Simpan_Data.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Simpan_Data.setForeground(new java.awt.Color(176, 58, 48));
        Simpan_Data.setText("SIMPAN");
        Simpan_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpan_DataActionPerformed(evt);
            }
        });

        Lanjutkan.setBackground(new java.awt.Color(217, 217, 217));
        Lanjutkan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lanjutkan.setForeground(new java.awt.Color(176, 58, 48));
        Lanjutkan.setText("KEMBALI");
        Lanjutkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanjutkanActionPerformed(evt);
            }
        });

        Hapus_Data.setBackground(new java.awt.Color(217, 217, 217));
        Hapus_Data.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Hapus_Data.setForeground(new java.awt.Color(176, 58, 48));
        Hapus_Data.setText("HAPUS ");
        Hapus_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hapus_DataActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(217, 217, 217));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(176, 58, 48));
        jButton1.setText("EDIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbKodeMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnOK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOK.setForeground(new java.awt.Color(176, 58, 48));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        Penyewa_harga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Penyewa_harga.setForeground(new java.awt.Color(217, 217, 217));
        Penyewa_harga.setText("Harga / Hari");

        harga.setEditable(false);
        harga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        tabelPenyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPenyewa.setSelectionBackground(new java.awt.Color(176, 58, 48));
        tabelPenyewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPenyewaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabelPenyewaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPenyewa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Penyewa_No, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Penyewa_kodeMobil)
                                                .addGap(159, 159, 159))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(cmbKodeMobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnOK)
                                                .addGap(30, 30, 30)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Penyewa_Mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Penyewa_Nama)
                                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Penyewa_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Penyewa_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Penyewa_TglPinjam)
                                    .addComponent(tglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Penyewa_harga)
                                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Penyewa_Aplikasi))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Biodata_Penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Simpan_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Hapus_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lanjutkan))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Biodata_Penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Penyewa_Nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Penyewa_No, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Penyewa_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Penyewa_TglPinjam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglPinjam))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Penyewa_Mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Penyewa_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Penyewa_kodeMobil)
                    .addComponent(Penyewa_harga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbKodeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOK)
                        .addComponent(noPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Penyewa_Aplikasi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Hapus_Data)
                        .addComponent(jButton1)
                        .addComponent(Simpan_Data)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Lanjutkan)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String host = "jdbc:mysql://localhost:3306/rental_mobil",
            user = "root",
            pass = "";
            Connection con = (Connection) DriverManager.getConnection(host, user, pass);

            String No = no.getText();
            String Nama = nama.getText();
            String Nik = nik.getText();
            String Mobil = mobil.getText();
            String NoPolisi = noPolisi.getText();
            String TglPinjam = tglPinjam.getText();
            String Harga = harga.getText();
            

            Statement st = (Statement) con.createStatement();
            st.executeUpdate("UPDATE penyewa SET Nama='"+Nama+"', Nik='"+Nik+"', namaMobil='"+Mobil+"', noPolisi='"+NoPolisi+"', tglPinjam='"+TglPinjam+"', Harga='"+Harga+"'  WHERE No='"+No+"'");
        }catch(SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }

        table();
        del();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Hapus_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hapus_DataActionPerformed
        // TODO add your handling code here:
        try {
            String host = "jdbc:mysql://localhost:3306/rental_mobil",
            user = "root",
            pass = "";
            Connection con = (Connection) DriverManager.getConnection(host, user, pass);

            String No = no.getText();

            Statement st = (Statement) con.createStatement();
            st.executeUpdate("DELETE FROM penyewa WHERE (No) = '"+No+"'");
        }catch(SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }

        table();
        del();
    }//GEN-LAST:event_Hapus_DataActionPerformed

    private void LanjutkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanjutkanActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_LanjutkanActionPerformed

    private void Simpan_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpan_DataActionPerformed
        // TODO add your handling code here:
        try {
            String host = "jdbc:mysql://localhost:3306/rental_mobil",
            user = "root",
            pass = "";
            Connection con = (Connection) DriverManager.getConnection(host, user, pass);

            String No = no.getText();
            String Nama = nama.getText();
            String Nik = nik.getText();
            String Mobil = mobil.getText();
            String NoPolisi = noPolisi.getText();
            String TglPinjam = tglPinjam.getText();
            String Harga = harga.getText();

            Statement st = (Statement) con.createStatement();
            st.executeUpdate("INSERT INTO penyewa ( No, Nama, Nik, namaMobil, noPolisi, tglPinjam, Harga) VALUES ('"+No+"', '"+Nama+"', '"+Nik+"', '"+Mobil+"', '"+NoPolisi+"', '"+TglPinjam+"', '"+Harga+"')");

        }catch(SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }

        table();
        del();
    }//GEN-LAST:event_Simpan_DataActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void tglPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglPinjamActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String kodeMobil = cmbKodeMobil.getSelectedItem().toString();
        
        try {
            String host = "jdbc:mysql://localhost:3306/rental_mobil",
            user = "root",
            pass = "";
            
            Connection con = (Connection) DriverManager.getConnection(host, user, pass);
            PreparedStatement pst = con.prepareStatement("SELECT * FROM mobil WHERE kode = ?");
            pst.setString(1, kodeMobil);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()==true){
                mobil.setText(rs.getString(2) + " - " + rs.getString(3));
                noPolisi.setText(rs.getString(5));
                harga.setText(rs.getString(7));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void tabelPenyewaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPenyewaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelPenyewaMouseEntered

    private void tabelPenyewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPenyewaMouseClicked
	int row = tabelPenyewa.rowAtPoint(evt.getPoint());
        String No = tabelPenyewa.getValueAt(row, 0).toString();
        no.setText(No);
        String Nama = tabelPenyewa.getValueAt(row, 1).toString();
        nama.setText(Nama);
        String NIK = tabelPenyewa.getValueAt(row, 2).toString();
        nik.setText(NIK);
        String Mobil = tabelPenyewa.getValueAt(row, 3).toString();
        mobil.setText(Mobil);
        String NoPolisi = tabelPenyewa.getValueAt(row, 4).toString();
        noPolisi.setText(NoPolisi);
        String TglPinjam = tabelPenyewa.getValueAt(row, 5).toString();
        tglPinjam.setText(TglPinjam);
        String Harga = tabelPenyewa.getValueAt(row, 6).toString();
        harga.setText(Harga);          
    }//GEN-LAST:event_tabelPenyewaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Biodata_Penyewa;
    private javax.swing.JButton Hapus_Data;
    private javax.swing.JButton Lanjutkan;
    private javax.swing.JLabel Penyewa_Aplikasi;
    private javax.swing.JLabel Penyewa_Mobil;
    private javax.swing.JLabel Penyewa_NIK;
    private javax.swing.JLabel Penyewa_Nama;
    private javax.swing.JLabel Penyewa_No;
    private javax.swing.JLabel Penyewa_TglPinjam;
    private javax.swing.JLabel Penyewa_harga;
    private javax.swing.JLabel Penyewa_kodeMobil;
    private javax.swing.JLabel Penyewa_plat;
    private javax.swing.JButton Simpan_Data;
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbKodeMobil;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobil;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField no;
    private javax.swing.JTextField noPolisi;
    private javax.swing.JTable tabelPenyewa;
    private javax.swing.JTextField tglPinjam;
    // End of variables declaration//GEN-END:variables
}
